# Get packages from renv file ---------------------------------------------


#' Get vector of packages in lock file
#'
#' @param lockfilepath Must be the path to a lock file generated by RENV. If NULL it will look for renv.lock in project root
#'
#' @return A vector of package names
#' @export
#'
#' @importFrom magrittr %>%
packageVectorFromlockfile <- function(lockfilepath = NULL) {

  if(is.null(lockfilepath)) {
    # Set lockfilepath to be one from project
    print("Attempting to use lock file in root project directory")
    lockfilepath <- file.path(renv::project(), "renv.lock")
  }

  if(!file.exists(lockfilepath) || length(lockfilepath) == 0) {
    stop(paste0("Lock file doesn't exist at: "), lockfilepath)
  }

  lockload <- rjson::fromJSON(file = lockfilepath)

  lockload$Packages %>% names() %>% return()

}


#' Get vector of packages in lock file
#'
#' @param lockfilepath Must be the path to a lock file generated by RENV. If NULL it will look for renv.lock in project root.
#' @param ppa TRUE / FALSE - Output the ppa or the hardcoded link for external repos
#'
#' @return Printout of text to put in your Docker file
#' @export
lockFileDeps <- function(lockfilepath = NULL, ppa = TRUE) {

  packagevector <- packageVectorFromlockfile(lockfilepath)

  generateDockerText(packagevector, ppa)

}
